apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: three-tier-fullstack
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/Dharmendra7798/three-tier-app.git'
    targetRevision: main
    path: 'Kubernetes-Manifests-file'
    directory:
      recurse: true

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: three-tier

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true

